add linkedids endpoint
Geovation/usemap-rest pull request #18
Opened 2022-11-17 11:58 UTC by branmkam

endpoint added

2022-11-17 13:37 UTC, DaveBathnes submitted a review, later dismissed

2022-11-23 13:14 UTC, DaveBathnes requested changes

2022-11-23 13:14 UTC, DaveBathnes commented on app.py
> +@app.route("/features/ngd/<input>")
Do we need both? If we're deprecating the old one, remove the Ngd part of the route, and method name, and use that one in place

2022-11-23 13:27 UTC, branmkam commented
updated!

2022-11-23 13:38 UTC, DaveBathnes approved these changes

2022-11-23 13:39 UTC, merged